### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by DecimalTurn** [DecimalTurn/VBA-on-GitHub-Automations#79]
Test

**Comment by DecimalTurn** [comment]
Let's strap on your boots!

**Comment by DecimalTurn** [comment]
https://www.example.com

**Comment by IEvangelist** [comment]
I reported this upstream, the issue seems to be something related to the `GitHub.Octokit.SDK` that my `Actions.Octokit` library is relying on.

https://github.com/octokit/dotnet-sdk/issues/117
